version: '3.8'

services:

  jumpbox:
    image: ubuntu:latest
    container_name: jumpbox
    build: 
      context: .
      dockerfile: ./Dockerfiles/jumpbox.Dockerfile
    tty: true
    volumes:
      - .vol/jumpbox:/home
    environment:
      - SYS_NAME=jumpbox

  # server:
  #   image: ubuntu:latest
  #   container_name: server
  #   build: .
  #   tty: true
  #   volumes:
  #     - .vol/server:/home/ubuntu
  #   environment:
  #     - SYS_NAME=server

  # node-0:
  #   image: ubuntu:latest
  #   container_name: node-0
  #   build: .
  #   tty: true
  #   volumes:
  #     - .vol/node-0:/home/ubuntu
  #   environment:
  #     - SYS_NAME=node-0

  # node-1:
  #   image: ubuntu:latest
  #   container_name: node-1
  #   build: .
  #   tty: true
  #   volumes:
  #     - .vol/node-1:/home/ubuntu
  #   environment:
  #     - SYS_NAME=node-1


volumes:
  vol: